# Generated by Django 2.2.12 on 2021-01-26 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hcpro',
            name='isDeleted',
            field=models.BooleanField(default=False),
        ),
    ]
